### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Splamy** [ReSpeak/tsdeclarations#5]
- [ ] update details on how split/command packets get flagged
- [x] update commands in proto.md to refer to the *.csv file
- [x] clarify ^ as pow
- [x] make a note on modpow/montgomery in 2.5
- [x] Add tsbook update rules (see below)

tsbook update rules example:
```ocaml
:// order, cid, invokerid, invokername, invokeruid, reasonid, cpid
:// cid, invokerid, invokername, invokeruid, channel_order, channel_name, channel_topic, channel_flag_default, channel_flag_password, channel_flag_permanent, channel_flag_semi_permanent, channel_codec, channel_codec_quality, channel_needed_talk_power, channel_icon_id, channel_maxclients, channel_maxfamilyclients, channel_codec_latency_factor, channel_codec_is_unencrypted, channel_delete_delay, channel_flag_maxclients_unlimited, channel_flag_maxfamilyclients_unlimited, channel_flag_maxfamilyclients_inherited, channel_name_phonetic, cpid
:// cid, invokerid, invokername, invokeruid
# sdfsdf sdf sdf sdf sdf
ServerInit -> Connection+ ???
ChannelMoved -> Connection.Server.Channels[cid]
	cpid -> ParentChannelId
ChannelCreated -> Connection.Server.Channels[cid]+
	channel_order -> Order
	channel_name -> Name
	function_name -> (DeleteDelay)
	...
ChannelDeleted -> Connection.Server.Channels[cid]-
```
